### ISSUE TITLE
UnicodeDecodeError on build

### ISSUE THREAD

**Issue by The-Judge** [fedora-python/python-ethtool#46]
During build on Python 3.6.5 (`pip3 install ethtool==0.13`), I receive the following error:
```Collecting ethtool==0.13
  Downloading https://files.pythonhosted.org/packages/5e/b5/8af4daccd6ac8f548d8a1c96d5697fc0d424e47c7f5c76183107b8af6bd0/ethtool-0.13.tar.gz (44kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5lwqn5lb/ethtool/setup.py", line 94, in <module>
        long_description = f.read()
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1829: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5lwqn5lb/ethtool/
```
I have no idea what is wrong; ethtool module builds on other hosts. Is this a known issue with environment or something maybe?

**Comment by hroncok** [comment]
I cannot reproduce this. What's you operating system?

**Comment by hroncok** [comment]
What is the output of `locale` shell command?

**Comment by hroncok** [comment]
I can reproduce this with Python 3.5 and ASCII locale.

```$ LANG=C pip install ethtool
Collecting ethtool
  Using cached https://files.pythonhosted.org/packages/5e/b5/8af4daccd6ac8f548d8a1c96d5697fc0d424e47c7f5c76183107b8af6bd0/ethtool-0.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-avo1f256/ethtool/setup.py", line 94, in <module>
        long_description = f.read()
      File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1829: ordinal not in range(128)
```

**Comment by The-Judge** [comment]
Thank you for your incredibly fast reply!
I'm on CentOS 6.7 with Python 3.6.5 installed from iUS (package `python36u-3.6.5-1.ius.centos6.x86_64`).

Output of `locale` is:
```LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
